# Generated by Django 2.1.7 on 2020-08-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_article_son_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='son_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
